########################################################  base  ########################################################
server:
  port: 20002

#######################################################  nacos  ########################################################
nacos:
  node:
    address:
      one: 127.0.0.1:8848
      two: 127.0.0.1:8849
      three: 127.0.0.1:8850
#nacos註冊地址
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.node.address.one},${nacos.node.address.two},${nacos.node.address.three}

#######################################################  ribbon  #######################################################
#请求超时设置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#########################################################  db  #########################################################
#######################################################  redis  ########################################################