########################################################  base  ########################################################
server:
  port: 20003

#######################################################  ribbon  #######################################################
#请求超时设置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#######################################################  nacos  ########################################################
nacos:
  node:
    address:
      one: 127.0.0.1:8848
      two: 127.0.0.1:8849
      three: 127.0.0.1:8850
#nacos註冊地址
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.node.address.one},${nacos.node.address.two},${nacos.node.address.three}

#########################################################  db  #########################################################
  #配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?setUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Rl123456
#######################################################  redis  ########################################################

#######################################################  test  #########################################################
bfr:
  refresh:
    test:
      name: 测试测试而已===5